# Generated by Django 3.2.14 on 2023-02-28 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
