# Generated by Django 3.2.14 on 2023-02-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_comment_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='blogpost_comment', to='Post.Comment'),
        ),
    ]
