# Generated by Django 3.2.14 on 2023-02-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
