# Generated by Django 3.2.14 on 2023-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_remove_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='blog_comments', to='Post.Comment'),
        ),
    ]
