# Generated by Django 3.2.14 on 2023-02-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
