# Generated by Django 3.2.14 on 2023-02-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_staff_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
