# Generated by Django 3.2.14 on 2023-02-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20230227_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
